export const GET_COUNTRY_REQUESTED ='GET_COUNTRY_REQUESTED'
export const GET_COUNTRY_SUCCESS ='GET_COUNTRY_SUCCESS'
export const GET_COUNTRY_FAILED ='GET_COUNTRY_FAILED'

export const GET_CITY_REQUESTED ='GET_CITY_REQUESTED'
export const GET_CITY_SUCCESS ='GET_CITY_SUCCESS'
export const GET_CITY_FAILED ='GET_CITY_FAILED'





