version: '3.7'
services:
  frontend:
    build:
      context: .
    command: npx serve -s build
    expose:
      - 3000
    networks:
      - frontend_network

  nginx:
    build: ./nginx
    ports:
      - ${APP_PORT}:80
    depends_on:
      - frontend
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge