export const GET_CONTACT_REQUESTED ='GET_CONTACT_REQUESTED'
export const GET_CONTACT_SUCCESS ='GET_CONTACT_SUCCESS'
export const GET_CONTACT_FAILED ='GET_CONTACT_FAILED'

export const GET_CONTACT_DETAILS_REQUESTED ='GET_CONTACT_DETAILS_REQUESTED'
export const GET_CONTACT_DETAILS_SUCCESS ='GET_CONTACT_DETAILS_SUCCESS'
export const GET_CONTACT_DETAILS_FAILED ='GET_CONTACT_DETAILS_FAILED'

export const GET_CONTACT_INVOICE_REQUESTED ='GET_CONTACT_INVOICE_REQUESTED'
export const GET_CONTACT_INVOICE_SUCCESS ='GET_CONTACT_INVOICE_SUCCESS'
export const GET_CONTACT_INVOICE_FAILED ='GET_CONTACT_INVOICE_FAILED'

export const GET_CONTACT_INVOICE_SETTING_REQUESTED ='GET_CONTACT_INVOICE_SETTING_REQUESTED'
export const GET_CONTACT_INVOICE_SETTING_SUCCESS ='GET_CONTACT_INVOICE_SETTING_SUCCESS'
export const GET_CONTACT_INVOICE_SETTING_FAILED ='GET_CONTACT_INVOICE_SETTING_FAILED'

export const UPDATE_CONTACT_INVOICE_SETTING_REQUESTED ='UPDATE_CONTACT_INVOICE_SETTING_REQUESTED'
export const UPDATE_CONTACT_INVOICE_SETTING_SUCCESS ='UPDATE_CONTACT_INVOICE_SETTING_SUCCESS'
export const UPDATE_CONTACT_INVOICE_SETTING_FAILED ='UPDATE_CONTACT_INVOICE_SETTING_FAILED'

export const GET_ALLCONTACT_REQUESTED ='GET_ALLCONTACT_REQUESTED'
export const GET_ALLCONTACT_SUCCESS ='GET_ALLCONTACT_SUCCESS'
export const GET_ALLCONTACT_FAILED ='GET_ALLCONTACT_FAILED'

export const ADD_CONTACT_REQUESTED ='ADD_CONTACT_REQUESTED'
export const ADD_CONTACT_SUCCESS ='ADD_CONTACT_SUCCESS'
export const ADD_CONTACT_FAILED ='ADD_CONTACT_FAILED'

export const DELETE_CONTACT_REQUESTED ='DELETE_CONTACT_REQUESTED'
export const DELETE_CONTACT_SUCCESS ='DELETE_CONTACT_SUCCESS'
export const DELETE_CONTACT_FAILED ='DELETE_CONTACT_FAILED'



export const SET_CONTACT_SUCCESS_ALERT ='SET_CONTACT_SUCCESS_ALERT'
export const SET_CONTACT_ERROR_ALERT ='SET_CONTACT_ERROR_ALERT'