export const GET_ROLE_REQUESTED ='GET_ROLE_REQUESTED'
export const GET_ROLE_SUCCESS ='GET_ROLE_SUCCESS'
export const GET_ROLE_FAILED ='GET_ROLE_FAILED'

export const GET_USERROLE_REQUESTED ='GET_USERROLE_REQUESTED'
export const GET_USERROLE_SUCCESS ='GET_USERROLE_SUCCESS'
export const GET_USERROLE_FAILED ='GET_USERROLE_FAILED'



