export const GET_SERVICE_REQUESTED ='GET_SERVICE_REQUESTED'
export const GET_SERVICE_SUCCESS ='GET_SERVICE_SUCCESS'
export const GET_SERVICE_FAILED ='GET_SERVICE_FAILED'

export const GET_CONTACTSERVICE_REQUESTED ='GET_CONTACTSERVICE_REQUESTED'
export const GET_CONTACTSERVICE_SUCCESS ='GET_CONTACTSERVICE_SUCCESS'
export const GET_CONTACTSERVICE_FAILED ='GET_CONTACTSERVICE_FAILED'

export const ADD_SERVICE_REQUESTED ='ADD_SERVICE_REQUESTED'
export const ADD_SERVICE_SUCCESS ='ADD_SERVICE_SUCCESS'
export const ADD_SERVICE_FAILED ='ADD_SERVICE_FAILED'





