export const GET_CHARTACCOUNT_REQUESTED ='GET_CHARTACCOUNT_REQUESTED'
export const GET_CHARTACCOUNT_SUCCESS ='GET_CHARTACCOUNT_SUCCESS'
export const GET_CHARTACCOUNT_FAILED ='GET_CHARTACCOUNT_FAILED'


export const ADD_CHART_OF_ACCOUNT_REQUESTED = "ADD_CHART_OF_ACCOUNT_REQUESTED"
export const ADD_CHART_OF_ACCOUNT_SUCCESS = "ADD_CHART_OF_ACCOUNT_SUCCESS"
export const ADD_CHART_OF_ACCOUNT_FAILED = "ADD_CHART_OF_ACCOUNT_FAILED"


export const SET_CHART_OF_ACCOUNT_SUCCESS_ALERT = "SET_CHART_OF_ACCOUNT_SUCCESS_ALERT"
export const SET_CHART_OF_ACCOUNT_ERROR_ALERT = "SET_CHART_OF_ACCOUNT_ERROR_ALERT"





