export const GET_INVOICE_REQUESTED ='GET_INVOICE_REQUESTED'
export const GET_INVOICE_SUCCESS ='GET_INVOICE_SUCCESS'
export const GET_INVOICE_FAILED ='GET_INVOICE_FAILED'

export const GET_INVOICEDETAILS_REQUESTED ='GET_INVOICEDETAILS_REQUESTED'
export const GET_INVOICEDETAILS_SUCCESS ='GET_INVOICEDETAILS_SUCCESS'
export const GET_INVOICEDETAILS_FAILED ='GET_INVOICEDETAILS_FAILED'






